"""Public exports for the auth package.

Prefer importing auth domain objects from here instead of reaching into service,
model, schema, or exception modules directly.
"""

from backend.auth.exceptions import (
    AuthDatabaseError,
    AuthError,
    AuthExternalServiceError,
    AuthValidationError,
    DeveloperAccessDenied,
    DeveloperProfileError,
    DeveloperProfileNotSet,
    DeveloperStoragePathError,
    FirebaseUserError,
    InstitutionAssignmentError,
    InstitutionCreateError,
    InstitutionError,
    InstitutionNotFound,
    InstitutionReadError,
    InstitutionSeedError,
    InstitutionValidationError,
    RoleAssignmentError,
    RoleCreateError,
    RoleError,
    RoleNotFound,
    RoleReadError,
    RoleSeedError,
    UserCreateError,
    UserDeleteError,
    UserError,
    UserNotFound,
    UserReadError,
    UserUpdateError,
    UserValidationError,
)
from backend.auth.model import (
    DeveloperProfile,
    Institution,
    Role,
    User,
    UserRoleLink,
)
from backend.auth.schemas import (
    CreateUserFullPayload,
    InstitutionRead,
    RoleRead,
    UpdateUserInstitution,
    UpdateUserRole,
    UserBase,
    UserCreate,
    UserDetailRead,
    UserInstResponse,
    UserRead,
    UserRoleResponse,
    UserRoles,
    UserUpdate,
    ValidInstitutions,
)
from backend.auth.services.developer_access import (
    AccessDecision,
    DeveloperAccessService,
)
from backend.auth.services.institution import InstitutionDB
from backend.auth.services.role import RoleDB
from backend.auth.services.user import UserDB
from backend.auth.services.user_manager import UserManager

__all__ = [
    "AccessDecision",
    "AuthDatabaseError",
    "AuthError",
    "AuthExternalServiceError",
    "AuthValidationError",
    "CreateUserFullPayload",
    "DeveloperAccessDenied",
    "DeveloperAccessService",
    "DeveloperProfile",
    "DeveloperProfileError",
    "DeveloperProfileNotSet",
    "DeveloperStoragePathError",
    "FirebaseUserError",
    "Institution",
    "InstitutionAssignmentError",
    "InstitutionCreateError",
    "InstitutionDB",
    "InstitutionError",
    "InstitutionNotFound",
    "InstitutionRead",
    "InstitutionReadError",
    "InstitutionSeedError",
    "InstitutionValidationError",
    "Role",
    "RoleAssignmentError",
    "RoleCreateError",
    "RoleDB",
    "RoleError",
    "RoleNotFound",
    "RoleRead",
    "RoleReadError",
    "RoleSeedError",
    "UpdateUserInstitution",
    "UpdateUserRole",
    "User",
    "UserBase",
    "UserCreate",
    "UserCreateError",
    "UserDB",
    "UserDeleteError",
    "UserDetailRead",
    "UserError",
    "UserInstResponse",
    "UserManager",
    "UserNotFound",
    "UserRead",
    "UserReadError",
    "UserRoleLink",
    "UserRoleResponse",
    "UserRoles",
    "UserUpdate",
    "UserUpdateError",
    "UserValidationError",
    "ValidInstitutions",
]
