"""Added status enum to question

Revision ID: 01d7577e4a0f
Revises: cb98fbbb525a
Create Date: 2025-12-30 15:24:05.102357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '01d7577e4a0f'
down_revision: Union[str, Sequence[str], None] = 'cb98fbbb525a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('ARCHIVED', 'DRAFT', 'PUBLISHED', name='status'), server_default=sa.text("'draft'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
