"""Ensure that the database schema has role name as string

Revision ID: 0246f7edabc7
Revises: 524be2808ab1
Create Date: 2025-12-16 15:14:01.830313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0246f7edabc7'
down_revision: Union[str, Sequence[str], None] = '524be2808ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=1)

    # ### end Alembic commands ###
