"""Added source column to question runtime

Revision ID: 0eeffadb4d7f
Revises: 1e6a44a08b31
Create Date: 2026-07-07 13:15:27.426464

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0eeffadb4d7f"
down_revision: str | Sequence[str] | None = "1e6a44a08b31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    source_type = sa.Enum(
        "MANUAL", "CONFIG_FILE", "INFERRED", name="runtimeconfigsource"
    )
    source_type.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source",
                sa.Enum(
                    "MANUAL", "CONFIG_FILE", "INFERRED", name="runtimeconfigsource"
                ),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.drop_column("source")

    # ### end Alembic commands ###
