"""Added runtime model for question

Revision ID: 1e6a44a08b31
Revises: 67b79c7d15ad
Create Date: 2026-07-07 11:48:48.610534

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e6a44a08b31"
down_revision: str | Sequence[str] | None = "67b79c7d15ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_runtime",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("JAVASCRIPT", "PYTHON", name="runtimelanguage"),
            nullable=False,
        ),
        sa.Column("entry", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("func_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_runtime_language"), ["language"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_runtime_language"))

    op.drop_table("question_runtime")
    # ### end Alembic commands ###
