"""Updated the question attempt model to include timestamp, quiz data, and submitted answer

Revision ID: 4d9981184ac8
Revises: d2ad86afaef9
Create Date: 2025-12-16 14:05:58.223416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d9981184ac8'
down_revision: Union[str, Sequence[str], None] = 'd2ad86afaef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_language_link')
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_id'))
        batch_op.drop_index(batch_op.f('ix_language_name'))

    op.drop_table('language')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_title'))

    op.drop_table('question')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_name'))

    op.drop_table('topic')
    op.drop_table('institution')
    op.drop_table('questionreview')
    op.drop_table('user_role_link')
    with op.batch_alter_table('question_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_type_name'))

    op.drop_table('question_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('question_ownership_link')
    op.drop_table('question_qtype_link')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    op.drop_table('question_attempt_link')
    op.drop_table('question_topic_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_topic_link',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('topic_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    op.create_table('question_attempt_link',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'user_id')
    )
    op.create_table('role',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=9), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=False)

    op.create_table('question_qtype_link',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('qtype_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['qtype_id'], ['question_type.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'qtype_id')
    )
    op.create_table('question_ownership_link',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    sa.Column('can_view', sa.BOOLEAN(), nullable=False),
    sa.Column('can_edit', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'user_id')
    )
    op.create_table('user',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('fb_id', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('institution_id', sa.CHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    op.create_table('question_type',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_type_name'), ['name'], unique=1)

    op.create_table('user_role_link',
    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('questionreview',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('reviewer_id', sa.CHAR(length=32), nullable=False),
    sa.Column('reviewed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'reviewer_id')
    )
    op.create_table('institution',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=5), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_topic_id'), ['id'], unique=False)

    op.create_table('question',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('isAdaptive', sa.BOOLEAN(), nullable=False),
    sa.Column('ai_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('local_path', sa.VARCHAR(), nullable=True),
    sa.Column('blob_path', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_id'), ['id'], unique=False)

    op.create_table('language',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_language_id'), ['id'], unique=False)

    op.create_table('question_language_link',
    sa.Column('question_id', sa.CHAR(length=32), nullable=False),
    sa.Column('language_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'language_id')
    )
    # ### end Alembic commands ###
