"""Updated the userroles to explicitly use an Enum

Revision ID: 524be2808ab1
Revises: 4d9981184ac8
Create Date: 2025-12-16 15:08:28.047051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '524be2808ab1'
down_revision: Union[str, Sequence[str], None] = '4d9981184ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_attempt_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_data', sa.JSON(), nullable=False),
    sa.Column('submitted_answer', sa.JSON(), nullable=False),
    sa.Column('attemption_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'question_id', 'user_id')
    )
    with op.batch_alter_table('question_attempt_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_attempt_link_id'), ['id'], unique=False)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=False)

    with op.batch_alter_table('question_attempt_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_attempt_link_id'))

    op.drop_table('question_attempt_link')
    # ### end Alembic commands ###
