"""Added description and display name to question type

Revision ID: 67b79c7d15ad
Revises: 9755f17c73a6
Create Date: 2026-07-03 16:33:45.729460

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67b79c7d15ad"
down_revision: str | Sequence[str] | None = "9755f17c73a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_type", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_type", schema=None) as batch_op:
        batch_op.drop_column("description")
        batch_op.drop_column("display_name")

    # ### end Alembic commands ###
