"""Added some new columns and constraint to the database

Revision ID: 9755f17c73a6
Revises: 01a9cae971bd
Create Date: 2026-07-03 14:44:56.142712

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9755f17c73a6"
down_revision: str | Sequence[str] | None = "01a9cae971bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


qtype = sa.Enum("MC", "MCQ", "MA", "TF", "FB", "NUM", name="qtype")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    qtype.create(op.get_bind(), checkfirst=True)
    op.execute("""
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type
        WHERE typname = 'qtype'
    ) THEN
        CREATE TYPE qtype AS ENUM (
            'MC',
            'MCQ',
            'MA',
            'TF',
            'FB',
            'NUM'
        );
    END IF;
END $$;

-- Create any missing NUM links.
INSERT INTO question_qtype_link (question_id, qtype_id)
SELECT
    question_id,
    (
        SELECT id
        FROM question_type
        WHERE name = 'numerical'
    )
FROM question_qtype_link
WHERE qtype_id IN (
    SELECT id
    FROM question_type
    WHERE name IN (
        'computational',
        'derivation',
        'numeric',
        'analysis'
    )
)
ON CONFLICT DO NOTHING;

-- Remove the obsolete links.
DELETE FROM question_qtype_link
WHERE qtype_id IN (
    SELECT id
    FROM question_type
    WHERE name IN (
        'computational',
        'derivation',
        'numeric',
        'analysis'
    )
);

-- Remove the obsolete lookup values.
DELETE FROM question_type
WHERE name IN (
    'computational',
    'derivation',
    'numeric',
    'analysis'
);

-- Rename the remaining lookup value.
UPDATE question_type
SET name = CASE
    WHEN name IN ('multiple-choice', 'multiple_choice', 'mc') THEN 'MC'
    WHEN name IN ('multiple-choice-question', 'multiple_choice_question', 'mcq') THEN 'MCQ'
    WHEN name IN ('multiple-answer', 'multiple_answer', 'ma') THEN 'MA'
    WHEN name IN ('true-false', 'true_false', 'tf') THEN 'TF'
    WHEN name IN ('fill-in-the-blank', 'fill_in_the_blank', 'fb') THEN 'FB'
    WHEN name IN ('numerical', 'number', 'num') THEN 'NUM'
    ELSE name
END;

-- Convert the column to the enum.
ALTER TABLE question_type
ALTER COLUMN name
TYPE qtype
USING upper(name)::qtype;
""")

    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "supports_python",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "supports_javascript",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_type", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.Enum("MC", "MCQ", "MA", "TF", "FB", "NUM", name="qtype"),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.alter_column(
            "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.alter_column(
            "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
        )
        batch_op.drop_column("supports_javascript")
        batch_op.drop_column("supports_python")

    # ### end Alembic commands ###
