"""Made the message content be json

Revision ID: a04f5e97da08
Revises: bc3da3982d78
Create Date: 2026-05-14 15:32:10.042901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a04f5e97da08"
down_revision: Union[str, Sequence[str], None] = "bc3da3982d78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=sa.VARCHAR(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            postgresql_using="content::jsonb",
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.alter_column(
            "content",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.VARCHAR(),
            nullable=False,
        )

    # ### end Alembic commands ###
