"""Added is correct field to question attempt

Revision ID: cb98fbbb525a
Revises: 0246f7edabc7
Create Date: 2025-12-22 16:03:25.387545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb98fbbb525a'
down_revision: Union[str, Sequence[str], None] = '0246f7edabc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attempt_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_attempt_link', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
