"""Added unique constraint for runtime model

Revision ID: e4f88de198c8
Revises: 0eeffadb4d7f
Create Date: 2026-07-08 12:12:43.345716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4f88de198c8"
down_revision: str | Sequence[str] | None = "0eeffadb4d7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""

-- SELECT * from question_runtime;
DELETE FROM question_runtime
WHERE id IN (
    SELECT id
    FROM (
        SELECT
            id,
            ROW_NUMBER() OVER (
                PARTITION BY question_id
                ORDER BY id
            ) AS rn
        FROM question_runtime
    ) duplicates
    WHERE rn > 1
);
select * from question_runtime;

""")

    op.drop_index(
        "uq_question_runtime_default_enabled",
        table_name="question_runtime",
        if_exists=True,
    )
    with op.batch_alter_table(
        "question_runtime",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            "uq_question_runtime_default_enabled",
            ["question_id"],
            unique=True,
            postgresql_where=sa.text("is_default=true AND enabled = true"),
            sqlite_where=sa.text("is_default = 1 AND enabled = 1"),
        )
        batch_op.create_unique_constraint(
            "uq_question_runtime_language", ["question_id", "language"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.drop_constraint("uq_question_runtime_language", type_="unique")
        batch_op.drop_index(
            "uq_question_runtime_default_enabled",
            postgresql_where=sa.text("is_default=true AND enabled = true"),
            sqlite_where=sa.text("is_default = 1 AND enabled = 1"),
        )

    # ### end Alembic commands ###
