"""Created a table question view

Revision ID: f9590abacf77
Revises: e4f88de198c8
Create Date: 2026-07-09 12:04:07.371874

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f9590abacf77"
down_revision: str | Sequence[str] | None = "e4f88de198c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

query = """
CREATE OR REPLACE VIEW question_table_view AS
SELECT
    "question"."id" AS "question_id",
    "developer_profile"."user_id" AS "owner_id",
    "developer_profile"."id" AS "developer_profile_id",
    "question"."title",
    "institution"."id" AS "institution_id",
    "institution"."name" AS "institution",
    "user"."email" AS "created_by",
    "question"."status",
    array_agg(DISTINCT "topic"."name" ORDER BY "topic"."name") AS "topics",
    array_agg(DISTINCT "question_type"."name" ORDER BY "question_type"."name") AS "question_type",
    coalesce(
        array_agg(DISTINCT "question_runtime"."language" ORDER BY "question_runtime"."language")
            FILTER (WHERE "question_runtime"."language" IS NOT NULL),
        '{}'
    ) AS "available_runtimes",
    "question"."created_at",
    "question"."updated_at"
FROM "question"
JOIN "question_topic_link"
    ON "question_topic_link"."question_id" = "question"."id"
JOIN "topic"
    ON "topic"."id" = "question_topic_link"."topic_id"
JOIN "question_qtype_link"
    ON "question_qtype_link"."question_id" = "question"."id"
JOIN "question_type"
    ON "question_type"."id" = "question_qtype_link"."qtype_id"
LEFT JOIN "question_runtime"
    ON "question_runtime"."question_id" = "question"."id"
JOIN "developer_profile"
    ON "developer_profile"."id" = "question"."created_by_id"
JOIN "user"
    ON "user"."id" = "developer_profile"."user_id"
JOIN "institution"
    ON "user"."institution_id" = "institution"."id"
GROUP BY
    "question"."id",
    "developer_profile"."user_id",
    "developer_profile"."id",
    "question"."title",
    "institution"."id",
    "institution"."name",
    "user"."email",
    "question"."status",
    "question"."created_at",
    "question"."updated_at";
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS question_table_view;")
    op.execute(query)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS question_table_view;")
    pass
    # ### end Alembic commands ###
